### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by andrei-markeev** [camarojs/redis#20]
## Environment

+ Node version: v14.16.0
+ Redis Server version: 6.0.14
+ Redis protocol version: 2
+ Camaro Redis version: 2.4.0

## Describe the bug

From time to time, I'm getting this error:

```
(node:5876) UnhandledPromiseRejectionWarning:
    Redis Reply Error: NOAUTH Authentication required.
        at Parser.parseSimpleError (C:\home\site\wwwroot\deps.js:382:14)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## To Reproduce

Code to reproduce the behavior:

``` js
const { ClientV2: Client } = require('@camaro/redis')
const client = new Client({
    host: "<remote redis server host>",
    password: "testpass"
});

async function test() {
    await client.SET('bar', 'bar')
    const reply = await client.GET('bar')
    console.log(reply) // 'bar'
}

test().then(() => process.exit(0));

```

**Additional context**

I think, what happens is:

1. I initialize the client - it starts connecting to the Redis server
2. I start doing my stuff, and run some redis commands (before connection is established) - these go to the buffer
3. Connection to server is established, authentication command is issued
4. Client starts sending the commands to the server - but first commands are those from the buffer

**Comment by andrei-markeev** [comment]
some additional information on that:

1. I tried adding a delay before sending commands, but that didn't help
2. I think it might be related to the reconnects, but I am not sure

**Comment by andrei-markeev** [comment]
Just an update: adding PING didn't help, still getting same error from time to time (couple times per day).
NOAUTH error always seems to happen on the first command sent to redis (although cannot tell with 100% certainty because stack trace is not showing where the error originates).
